# Use Python 3.8.10 base image
FROM python:3.8.10

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY ./src /app

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Run the application
CMD ["python", "app.py"]
